### ISSUE TITLE
Perf degenerated ~20% install-package comparing NuGetV2, V3 providers

### ISSUE THREAD

**Issue by jianyunt** [brywang-msft/NuGetProvider#3]
V3 Nuget provider
``` PowerShell
Measure-Command{ install-package bootstrap -ProviderName nuget -Scope CurrentUser  -Source nugetv3  -force}



Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 5
Milliseconds      : 122
Ticks             : 51220351
TotalDays         : 5.92828136574074E-05
TotalHours        : 0.00142278752777778
TotalMinutes      : 0.0853672516666667
TotalSeconds      : 5.1220351
TotalMilliseconds : 5122.0351

```

V2 NugetProvider
Measure-Command{ install-package bootstrap -ProviderName nuget -Scope CurrentUser  -Source nuget  -force}

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 3
Milliseconds      : 963
Ticks             : 39635879
TotalDays         : 4.58748599537037E-05
TotalHours        : 0.00110099663888889
TotalMinutes      : 0.0660597983333333
TotalSeconds      : 3.9635879
TotalMilliseconds : 3963.5879

**Comment by brywang-msft** [comment]
Performance decrease is expected. There's no way to get around the extra call in this case.
